# Generated by Django 4.1.2 on 2022-10-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_hackathon_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='media/users/avatar.png', upload_to='media/users'),
        ),
    ]
